//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamBuilder.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAYER
    {
        public int ID { get; set; }
        public string FNAME { get; set; }
        public string LNAME { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<bool> GENDER { get; set; }
        public string ROSTERNOTE { get; set; }
        public string PLAYERNOTE { get; set; }
        public string SEASONSPLAYED { get; set; }
        public Nullable<int> TEAMID { get; set; }
        public string DIVISION { get; set; }
    
        public virtual TEAM TEAM { get; set; }
    }
}
