//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamBuilder.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TEAM()
        {
            this.COACHes = new HashSet<COACH>();
            this.PLAYERs = new HashSet<PLAYER>();
            this.ASSISTANTs = new HashSet<ASSISTANT>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> PLAYER1 { get; set; }
        public Nullable<int> PLAYER2 { get; set; }
        public Nullable<int> PLAYER3 { get; set; }
        public Nullable<int> PLAYER4 { get; set; }
        public Nullable<int> PLAYER5 { get; set; }
        public Nullable<int> PLAYER6 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COACH> COACHes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLAYER> PLAYERs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASSISTANT> ASSISTANTs { get; set; }
    }
}
